all:
	mkdir EJECUTABLES
	g++ -Wall -o EJECUTABLES/collatz collatz/collatz.cc
	g++ -Wall -o EJECUTABLES/statistic statistic/statistic.cc
	g++ -Wall -o EJECUTABLES/random_numbers random_numbers/random_numbers.cc
	g++ -Wall -o EJECUTABLES/longest_shortest longest_shortest/longest_shortest.cc
	g++ -Wall -o EJECUTABLES/cuadrado_asteriscos cuadrado_asteriscos/cuadrado_asteriscos.cc
	g++ -Wall -o EJECUTABLES/leap_year leap_year/leap_year.cc
	g++ -Wall -o EJECUTABLES/time_decomposition time_decomposition/time_decomposition.cc
	g++ -Wall -o EJECUTABLES/sumatorio_tres_ultimos_digitos sumatorio_tres_ultimos_digitos/sumatorio_tres_ultimos_digitos.cc
	g++ -Wall -o EJECUTABLES/temperaturas temperaturas/temperaturas.cc
	g++ -Wall -o EJECUTABLES/dividers dividers/dividers.cc
	g++ -Wall -o EJECUTABLES/sumatorio_de_digitos sumatorio_de_digitos/sumatorio_de_digitos.cc
clean:
	rm -r EJECUTABLES