all:
	g++ -o EJECUTABLES/data_types data_types/data_types.cc
	g++ -o EJECUTABLES/short_circuit short_circuit/short_circuit.cc
	g++ -o EJECUTABLES/references references/references.cc
	g++ -o EJECUTABLES/change_case change_case/change_case.cc
	g++ -o EJECUTABLES/boolean_operators boolean_operators/boolean_operators.cc
	g++ -o EJECUTABLES/arithmetic_operators arithmetic_operators/arithmetic_operators.cc

EJECUTABLES/data_types: data_types/data_types.cc
	g++ -o EJECUTABLES/data_types data_types/data_types.cc

EJECUTABLES/short_circuit: short_circuit/short_circuit.cc
	g++ -o EJECUTABLES/short_circuit short_circuit/short_circuit.cc

EJECUTABLES/references: references/references.cc
	g++ -o EJECUTABLES/references references/references.cc

EJECUTABLES/change_case: change_case/change_case.cc
	g++ -o EJECUTABLES/change_case change_case/change_case.cc

EJECUTABLES/boolean_operators: boolean_operators/boolean_operators.cc
	g++ -o EJECUTABLES/boolean_operators boolean_operators/boolean_operators.cc

EJECUTABLES/arithmetic_operators: arithmetic_operators/arithmetic_operators.cc
	g++ -o EJECUTABLES/arithmetic_operators arithmetic_operators/arithmetic_operators.cc

clean:
	rm EJECUTABLES/*