all:
	mkdir EJECUTABLES
	g++ -Wall -o EJECUTABLES/sum_of_fractions sum_of_fractions/sum_of_fractions.cc
	g++ -Wall -o EJECUTABLES/statistical_measures statistical_measures/statistical_measures.cc
	g++ -Wall -o EJECUTABLES/sequential_search_in_an_array sequential_search_in_an_array/sequential_search_in_an_array.cc
	g++ -Wall -o EJECUTABLES/mersenne mersenne/mersenne.cc mersenne/funciones.cc
	g++ -Wall -o EJECUTABLES/maximum_sums maximum_sums/maximum_sums.cc
	g++ -Wall -o EJECUTABLES/maximum_of_each_sequence maximum_of_each_sequence/maximum_of_each_sequence.cc
	g++ -Wall -o EJECUTABLES/increasing_pairs increasing_pairs/increasing_pairs.cc
	g++ -Wall -o EJECUTABLES/equal_to_the_last_one equal_to_the_last_one/equal_to_the_last_one.cc
	g++ -Wall -o EJECUTABLES/counting_frequences counting_frequences/counting_frequences.cc
	g++ -Wall -o EJECUTABLES/caesar_cipher caesar_cipher/caesar_cipher.cc
	g++ -Wall -o EJECUTABLES/balanced_numbers balanced_numbers/balanced_numbers.cc
	g++ -Wall -o EJECUTABLES/armstrong armstrong/armstrong.cc armstrong/funciones.cc
clean:
	rm -r EJECUTABLES