all:
	mkdir EJECUTABLES
	g++ -Wall -o EJECUTABLES/division_and_remainder division_and_remainder/division_and_remainder.cc
	g++ -Wall -o EJECUTABLES/triangle triangle/triangle.cc
	g++ -Wall -o EJECUTABLES/max_int_tree_number max_int_tree_number/max_int_tree_number.cc
	g++ -Wall -o EJECUTABLES/how_many_seconds how_many_seconds/how_many_seconds.cc
	g++ -Wall -o EJECUTABLES/add_one_second add_one_second/add_one_second.cc
	g++ -Wall -o EJECUTABLES/elementos elementos/elementos.cc
	g++ -Wall -o EJECUTABLES/intervals intervals/intervals.cc
	g++ -Wall -o EJECUTABLES/sum_digits sum_digits/sum_digits.cc
	g++ -Wall -o EJECUTABLES/counting_a counting_a/counting_a.cc
	g++ -Wall -o EJECUTABLES/collatz collatz/collatz.cc
#division_and_remainder
#triangle
#max_int_tree_number
#how_many_seconds
#add_one_second 
#elementos
#intervals
#sum_digits
#counting_a
#collatz
clean:
	rm -r EJECUTABLES