all:
	mkdir EJECUTABLES
	g++ -Wall -o EJECUTABLES/aproximation_of_e aproximation_of_e/aproximation_of_e.cc
	g++ -Wall -o EJECUTABLES/divisors_in_order divisors_in_order/divisors_in_order.cc
	g++ -Wall -o EJECUTABLES/first_position first_position/first_position.cc
	g++ -Wall -o EJECUTABLES/harmonic_numbers harmonic_numbers/harmonic_numbers.cc
	g++ -Wall -o EJECUTABLES/harmonic_numbers_2 harmonic_numbers_2/harmonic_numbers_2.cc
	g++ -Wall -o EJECUTABLES/I-th I-th/I-th.cc
	g++ -Wall -o EJECUTABLES/looking_for_an_a looking_for_an_a/looking_for_an_a.cc
	g++ -Wall -o EJECUTABLES/parentheses parentheses/parentheses.cc
	g++ -Wall -o EJECUTABLES/primality primality/primality.cc
	g++ -Wall -o EJECUTABLES/three_words three_words/three_words.cc
clean:
	rm -r EJECUTABLES
